version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_forohub
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER={DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: forohub_app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      # Sobrescribimos el host para que Spring Boot use el contenedor MySQL
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./mediafile:/app/mediafile
    command: [ "java", "-jar", "app.jar" ]

volumes:
  mysql_data: